# your project's name
project_name = "rustxxx"

# code template path, default value: './mustache'
mustache_path = "/Volumes/code/temp/rust-web-server-mustache"

# code gen path, default value: './example', for example: './example', '/Volumes/hello/world'
example_path = "/Volumes/code/temp/"

[cargo_toml]
bin_name = "rustx" # bin's name of command 'cargo build --release'

[env]
database_url = "postgres://postgres:@localhost:5432/my_example" # database url
bind_address = "127.0.0.1:3030"                                 # server bind address

[vars]
package_name = "jvars"    #lib 'vars' package name
member_name = "just_vars" #lib 'vars' member name or folder name or module name

[server_lib]
package_name = "jserver_lib"
member_name = "just_server_lib"

[server_app]
package_name = "jserver_app"
member_name = "just_server_app"

[repository]
package_name = "jrepository"
member_name = "just_repository"

[domain]
package_name = "jdomain"
member_name = "just_domain"

[api]
package_name = "japi"
member_name = "just_api"

[search]
package_name = "jsearch"
member_name = "just_search"

[extra]
package_name = "jextra"
member_name = "just_extra"

[util]
package_name = "jutil"
member_name = "just_util"
