[package]
name = "trans"
version = "0.1.0"
edition = "2021"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
bench = false
path = "src/main.rs"
name = "trans"

[dependencies]
walkdir = "2"
dircpy = "0.3.8"
structopt = "0.3"
